steps:
# build the container image
- name: 'gcr.io/cloud-builders/java/mvn'
  args: ['clean', 'install']
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/symptomatic-backend:$COMMIT_SHA', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/symptomatic-backend:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'symptomatic-backend'
  - '--image'
  - 'gcr.io/$PROJECT_ID/symptomatic-backend:$COMMIT_SHA'
  - '--region'
  - 'europe-north1'
  - '--platform'
  - 'managed'
images:
- 'gcr.io/$PROJECT_ID/symptomatic-backend:$COMMIT_SHA'